pref("plasma5opt.colorScheme", "plasma5");
pref("plasma5opt.customColorScheme_att1", '#000000');
pref("plasma5opt.customColorScheme_att2", '#000000');
pref("plasma5opt.tabBorderStyle", "squared");
pref("plasma5opt.labelTextColor", false);
pref("plasma5opt.labelTextColor_att",'#3D3D3D');
pref("plasma5opt.iconColor", false);
pref("plasma5opt.iconColor_att", '#000000');
pref("plasma5opt.tabMinHeight", 27);
pref("plasma5opt.tabMinWidth", 100);
